#!/usr/bin/env bash

# make -C /usr/ports/lang/python3 install
# env PYTHON3=/usr/local/bin/python3
# pkg install cppzmq doxygen
git add CMakeLists.txt
git add make-FreeBSD
git commit -m "FreeBSD 12 : SEM lmdb "
git pull origin master
git push copy

git submodule init
git submodule update
#cd ~/monero
mkdir build
mkdir build/release
cd build/release

# cmake -D BUILD_TESTS=OFF -D WITHOUT_TREZOR -D CMAKE_BUILD_TYPE=release ../..
cmake ../..
 make